apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-volume
  labels:
    app: nginx-volume
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/cloud_user/html"
