apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-mysql
  labels:
    app: example-mysql
spec:
  selector:
    matchLabels:
      app: example-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: example-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
